ci9

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -11,29 +11,29 @@ jobs:
       - name: Checkout do Repositorio
         uses: actions/checkout@v4
 
-      - name: Detect package manager
-        id: detect-package-manager
-        run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+      # - name: Detect package manager
+      #   id: detect-package-manager
+      #   run: |
+      #     if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+      #       echo "manager=yarn" >> $GITHUB_OUTPUT
+      #       echo "command=install" >> $GITHUB_OUTPUT
+      #       echo "runner=yarn" >> $GITHUB_OUTPUT
+      #       exit 0
+      #     elif [ -f "${{ github.workspace }}/package.json" ]; then
+      #       echo "manager=npm" >> $GITHUB_OUTPUT
+      #       echo "command=ci" >> $GITHUB_OUTPUT
+      #       echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+      #       exit 0
+      #     else
+      #       echo "Unable to determine package manager"
+      #       exit 1
+      #     fi
 
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: '20.x'
-          cache: ${{ steps.detect-package-manager.outputs.manager }}
+          #cache: ${{ steps.detect-package-manager.outputs.manager }}
       #- run: npm install --global yarn
       #- run: CI=false
       #- run: yarn install
@@ -45,7 +45,7 @@ jobs:
         env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
           #ARGS: "-rltgoDzvO --delete"
-          ARGS: "-rlgoDzvc -i --delete"
+          ARGS: "-rlgoDzvc -i"
           #ARGS: "-rltDzvO --delete"
           #ARGS: "-rlgoDzvc --delete"
           #ARGS: "-rlgoDzvc -i --delete"
@@ -68,6 +68,7 @@ jobs:
               cd /www/wwwroot/evnt.carlosdj.com.br/
               yarn 
               yarn build
+              yarn pm2:restart
               
       
     
